language: node_js
node_js:
  - "node"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
branches:
  only:
    - master
notifications:
  email:
    on_failure: change
    on_success: change
script:
  -
before_deploy:
  - "echo 'ready?'"
  - yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
after_deploy:
  - "echo 'done?'"