sudo: false
language: node_js
warnings_are_errors: false
node_js:
- 10
branches:
  only:
  - master
notifications:
  email:
    on_failure: change
    on_success: change
cache:
  yarn: true
  directories:
  - node_modules
script:
- 
before_deploy:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  project: TavernOfCho/website
env:
  global:
  - secure: S3DvIvIGOl9hRhkqYAZmGFJb847inrkJ+c0BqpCN58FnjR1ngI7NawsOOBgZsHptreG5UMzYTOnpwDvEWcbdsp4b/2ODCvAFBURRc57HVoJDee+4+qmnSG9x6oqD5uHXRwYwr4C4XjGHmKEULXp/C7DSa6uprVyX+Nan0GwxyQ8nG2tKqwC2aMYVIDEV4VqamdKQcLj3supVkQSCG7taO5zeweDKlhGaKOZ+WmYYv6m8Z4OX2SqCQdreWIfef5r8puO7tv9JV2ezSX+P60Aa2nRdN0sXBLJpIjbmpBX1ZPDloHtECk1PpEpBye5zsL143doKWBKJDTRT6Dkxz2g+qSlGdi3In6xsEbYyjOFwqhNeQCUDEKU6nnwW5eEj8mnnxWcdK6a0AToF02Y1Y1+Fk9gXHvZVZUyGcFkngOzCTpaYFsaJ4K7xspzG5ZG6W27svbq09FnpXyY2hLWAHroxc3d23BKf/wZLWHpY2eFkPZN92y/zSHMu7x5+IVtz0Q5Gkwb+e5fEO9sPBY0tVT0nTImdtxU6TwumGqIz0vgW0M3M8BnolCa9sajXyrov4CUmZaniVB1bxvPqPsT9tSNJS1EDqYel0k80gEMN/3zr/014SAl8dXEMnX+WlKD/5lSFEvzMeZKsuUE4jX+qRAN7jVVgWQQmrHUfu2gYN7Xg8LI=
