language: node_js
node_js:
  - "10"
notifications:
  email:
    on_failure: change
    on_success: change
script:
  -
before_deploy:
  - "echo 'ready?'"
  - yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
after_deploy:
  - "echo 'done?'"