language: node_js
warnings_are_errors: false
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_failure: change
    on_success: change
node_js:
  - "node"
script:
  -
before_deploy:
  - yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: TavernOfCho/website