export const userConstants = {
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  RENEW_SUCCESS: 'USERS_RENEW_SUCCESS',
  RENEW_FAILURE: 'USERS_RENEW_FAILURE',
};
